# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  web:
    image: annotator_client
    build: .
    command: uwsgi --http 0.0.0.0:5000 --module annotator_client.wsgi:app
    env_file:
      - ./.flaskenv
    environment:
      - DATABASE_URI=sqlite:////db/annotator_client.db
    volumes:
      - ./annotator_client:/code/annotator_client
      - ./db/:/db/
    ports:
      - "5000:5000"
